[package]
name = "logcast"
version = "0.2.4"
edition = "2024"
description = "Simple helper to send logs via TCP"
license = "MIT"

[dependencies]
chrono = { version = "0.4", features = ["clock"] }
log = { version = "0.4.28", features = ["std"] }
